### ISSUE TITLE
nm_join_bayes: is use of fixed table okay?

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/bbr.bayes#96]
cc @seth127 @timwaterhouse @kylebaron

I'm wondering about the interaction of these two directions we decided to take with gh-75:

-   `submit_model` now tacks on its own table record for `run_sims` underneath so that we don't need to worry about doing extensive checking of a user-controlled table record.
    
    [9709c43](https://github.com/metrumresearchgroup/bbr.bayes/commit/9709c43f144295a6b8af10c07699b2f1e69d306d) (nmbayes submit\_model: write table for run\_sims, gh-75).

-   `run_sims` was renamed to `nm_join_bayes` and an `nm_join_bayes_quick` variant was added.
    
    [f2622db](https://github.com/metrumresearchgroup/bbr.bayes/commit/f2622db7567d55abd3cf4d82b1aeb82ca7119751) (nmbayes: rename run\_sims to nm\_join\_bayes, gh-75)
    
    [a100218](https://github.com/metrumresearchgroup/bbr.bayes/commit/a100218007240c25d8faa9fe9d6980f7c177d652) (nmbayes: export 'quick' wrapper around nm\_join\_bayes, gh-75).

`bbr::nm_join` supports specifying table file(s) via its `.files` argument. Given the new name, is it a problem that `nm_join_bayes` only reads in a behind-the-scenes table with a fixed set of columns?

**Comment by timwaterhouse** [comment]
@kyleam Is there a reason not to add the `.files` argument here? Would we then need to check that those tables contain the necessary columns? I guess that would be redundant.

**Comment by kyleam** [comment]
> Is there a reason not to add the `.files` argument here? Would we then need to check that those tables contain the necessary columns? I guess that would be redundant.

That last bit is pretty much what's making me stop and wonder whether these two directions aren't aligned.  If we think we do want to support the `.files` argument, then it seems like there's no point in continuing with the behind-the-scenes table because that was meant to avoid dealing with needing to worry about with arbitrary tables.

So my thinking is we either say

1. we want to add logic for `.files`, so let's rip out the complication of the behind-the-scenes table set up by `submit_mode.bbi_nmbayes_model`.

2. no, we don't want to support `.files` because of X.

For the implementation standpoint, I can't really think of any strong reasons.  Things might get a little messy with mapping the specified name to submodel name (e.g., I think that if the original table file name has a model ID in it, it will be replaced with the submodel ID), and for the table line parsing, we may need to do a bit of work on top of what nmrec gives us.

From the conceptual/scientific standpoint, is there any reason we wouldn't want to support arbitrary table files.?

**Comment by seth127** [comment]
Some notes today from offline discussion with @kyleam and @timwaterhouse:

# Proposal

My current take is that we should:

* Add a `files` argument to `nm_join_bayes()` and `nm_join_bayes_quick()`.
  * It should default to `bbr::nm_table_files(mod)`, [like `bbr::nm_join()` does](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L84) (i.e. grab all tables defined in the control stream)
* Revert `submit_model.bbi_nmbayes_model` to _not_ tack on the extra table that was added by 9709c43f144295a6b8af10c07699b2f1e69d306d
* If no table files are found...
  * For `nm_join_bayes_quick()`: error [like `bbr::nm_join()` does](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-tables.R#L99) (slightly more detail in comment [here](https://github.com/metrumresearchgroup/bbr/pull/603#issuecomment-1708951336))
  * For `nm_join_bayes()`: **Still do the simulation**. That would effectively give you **the input data joined to the newly simulated columns.**

# User Considerations

The primary questions I see here (looking for input from @kylebaron @timwaterhouse any other scientist user) are:

* Do you see any user-focused reason _not_ to have the `files` argument like `bbr::nm_join()` does? 
  * By "user-focused" I mean "_not_ implemention-related, but focused on giving the user what they actually want"
* Do you see any reason _not_ to simulate the new columns in `nm_join_bayes()` in the case when there are no actual table files being pulled in to the "join"?
  * We looked through the code a bit and couldn't find any place where the simulation was dependent on values coming out of a pre-existing table, but we may have missed something there.

## Other considerations

* @kyleam mentioned above that we added the table in 9709c43f144295a6b8af10c07699b2f1e69d306d in part "so that we don't need to worry about doing extensive checking of a user-controlled table record." It's not clear to me what this checking would have been... I think we just need to check that all tables have `join_col` in them, right?
  * We do some simple checks on the data `bbr::nm_join()` [here](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L113-L122)
  * I looked through the code a bit and I don't even see where we check that the tables coming in have `join_col` in them. Do we just let it error on the join?
* I was initially concerned about column collisions from allowing arbitrary tables come in, but we just drop any duplicates in `bbr::nm_join()` [here](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L188-L205). I would think we just do the same thing.
* Having `nm_join_bayes(..., files = bbr::nm_table_files(mod))` could necessitate some weird (impossible?) handling with this proposed behavior. Currently `bbr::nm_table_files` errors if no files are found, but we would want to catch that error and simulate the new columns instead. I guess we could just do `nm_join_bayes(..., files = NULL)` and then document the default and do the actual call in a `tryCatch()` inside the function.
* There is also [the `superset` argument](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L18-L22) in `bbr::nm_join()`. Do we want to support this?
  * If so, should we simulate values for rows that are in the input data but not the table files? Is this likely to cause any issues? (I don't fully understand the variety of reasons these rows may have been omitted from the tables...)
* `bbr::nm_join()` also has this [complex handling of `FIRSTONLY` tables](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L39-L51), in addition to [this row number check](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L148-L152) (which is what necessitates the `model_summary()` call...). I'm hoping we _don't_ need to implement any of that in `nm_join_bayes()` but we should make sure to discuss that.

**Comment by kyleam** [comment]
@seth127 Thanks for the write-up.

> "so that we don't need to worry about doing extensive checking of a user-controlled table record." It's not clear to me what this checking would have been... I think we just need to check that all tables have `join_col` in them, right?

Yes, that looks like bad word choice on my part (in particular "extensive"). I was probably including EPRED and friends with things we needed to check, but, as we discussed on the call, we don't think we actually need that.  (And, for a user of `*_quick`, having it missing if you didn't table it is obvious enough behavior.)

In addition to the join col, the other part that comes to mind is deciding which table file to use if there were multiple.  That's side stepped if there is a table argument that defaults to all tables.  And I was thinking we may need special handling for `nm_table_files`, but on second thought that should just work when called on the `bbi_nonmem_model` submodels.  (Perhaps still worth thinking how that function should behave if passed a top-level nmbayes mode; it's not currently a method.  But we don't need that here.)

**Comment by kylebaron** [comment]
Hi @seth127  and @kyleam  - 


- Agree that it would be nice to have the `.files` argument in play; more for outside users who might name these differently and for consistency; I think what @kyleam was getting at was most of the important handling for the table files is already in place
- I like this idea of passing `.files = NULL` and just skipping the whole table search and validate step and just simulate; didn't appreciate that the tables were not needed if we are simulating anyway, so could we only go down that road if users are opting the `quick` option? 
- I think we always need the row number check if it's a single column on which to join; been thinking about this and whether or not it would be good idea to table ID and a numbering row that resets with every ID but that's separate issue
- I'd like to keep `.superset` ... it's just so useful when you need it. 
- I don't use `FIRSTONLY` but I think it would be odd to not support that
- I don't remember what was going on under the hood in nm_join_bayes ... is there not a way to just lean on `nm_join()` to do `.superset` and `FIRSTONLY` if the table files are available?

**Comment by seth127** [comment]
@kyleam I looked into using `bbr::nm_join` under-the-hood a bit yesterday. Unfortunately, I'm seeing some potential problems. TL;DR 

* I'm skeptical that we can actually use `nm_join()` underneath without making some changes on the `bbr` side, or changing some of the currently planned `nm_join_bayes` behavior.
* I still like the idea of using `nm_join()`, especially if we want to support all the `nm_join()` behaviors we discussed [above](https://github.com/metrumresearchgroup/bbr.bayes/issues/96#issuecomment-1709465935). I really don't love the idea of re-implementing all of that in `bbr.bayes`, though that may end up being the best option.

<details><summary>`nm_join` behaviors discussed above</summary>

* [`.superset`](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L124-L127)
* [`FIRSTONLY`](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L153-L169)
* [row number check](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L118-L122)
* [ID check](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L134-L153)

</details>

_Note: by "current" bbr below, I'm talking about 1.7.0._

# Context

**These problems respectively hinge on two of our current functional requirements:**

1. Be able to use `nm_join_bayes()` on a model with _no table files_. We want to allow this to support the use case of joining newly simulated columns against the input data. 
2. Be able to pass custom data into `nm_join_bayes()` instead of getting the data from `nm_data()` (i.e. the data set used in the original model).

I'm going to discuss the technical issues that I see below but we probably also want to start a side discussion about whether or not we actually want to move forward with supporting these requirements.

## Requirement 1: supporting no table files

I detail some implementation details below, but these are very dependant on the answer to this user question: In this case, if we are going to take the raw input data and add the new simulated columns, **do we need to filter out any individuals that would've been ignored in the NONMEM model?**

_Side note: When we join against tables, this isn't an issue because tables have those individuals filtered out (and [we `left_join` against them](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L174) by default)_

<details><summary>Implementation details</summary>

This would essentially be passing `.files = NULL` or something like that. However, `nm_join` currently defaults to `.files = nm_table_files(.mod)`. Currently, `nm_table_files()` [errors if no tables are defined](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-tables.R#L99) in the control stream(s).

That would be easy enough to catch, but even if we _don't_ rely on `nm_table_files()`, `nm_join` currently [relies on `nm_tables()`](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L102) to do the heavy lifting. I can't find a way to pass the "no tables" case through the current implementation:



```r
nm_tables(MOD1, .files = NULL)
# Error in nm_join(MOD1, .files = NULL) :
# Assertion on '.files' failed: Must be of type 'character', not 'NULL'.

nm_tables(MOD1, .files = "")
# Reading data file: acop.csv
#   rows: 799
#   cols: 10
# 
# Reading 1
# Error in nm_file_impl(.mod) :
# Assertion on '.path' failed: File expected, but directory in place: '/data/home/sethg/metrumresearchgroup/bbr/inst/model/# nonmem/basic/1/'.

nm_tables(MOD1, .files = character())
# Reading data file: acop.csv
#   rows: 799
#   cols: 10
# 
# Error in nm_file.character(.files[.i]) :
# Assertion on '.mod' failed: May not be NA.
```

Now, this might be fine, because:

* It seems reasonable for `nm_join_bayes_quick()` to fail if no table files are found (for the same reason `nm_join()` fails: there's nothing to join)
* In this case, `nm_join_bayes()` could just skip the `nm_join()` call, and add the simulated columns directly to the data (either loaded with `nm_data()` or passed via `data` arg)

However, this would mean we _don't_ go through any of the `nm_join()` logic. Some of that isn't relevant if there are no tables (e.g. ID checking, `FIRSTONLY`) but the user question above becomes relevant: do we need to handle filtering to only individuals that weren't ignore by NONMEM.

</details>


## Requirement 2: passing custom data

**I'm actually not sure what the use case is here.** I believe this was originally a request from @KatherineKayMRG so we may need her (or someone else who knows) to clarify the need for this. Honestly, my hope is that, once we get clarity on the specific need, there might be another way to accomplish it that _doesn't_ involve passing custom data.

Assuming that we _do_ want to support this, I struggle to see how we do it without adding the same functionality (i.e. an optional `.data` arg) to `bbr::nm_join()`.

<details><summary>Implementation details</summary>

Neither `bbr::nm_join` nor `bbr::nm_tables()` (which `nm_join` currently [relies on](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L102)) allow the user to pass custom data. They simply take a model and pull the data with `nm_data()` ([here](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-join.R#L102-L103), then [here](https://github.com/metrumresearchgroup/bbr/blob/1.7.0/R/nm-tables.R#L57-L60)).

It's not clear that there's any use case for passing in custom data here. But if we _don't_ change this on the `bbr` side, then I see the following options:

1. Still use `nm_join()`, but then _replace_ all the data columns in the resulting df with the custom data. This is possible, but seems pretty inefficient and also possibly very error-prone. This also has potential to either lose rows or add rows, since we're first joining against the model data and then re-joining against the custom data. The more I think about this, the less I like it.
2. When the user passes custom data, _don't_ use `nm_join()` at all. However, this would mean we need to re-implement the all the join stuff on the `bbr.bayes` side. And at that point... what's the point of using `bbr::nm_join()` at all?

It's probably obvious that I don't like either of those options, so I am certainly open to any other ones that anyone can think of.

</details>

**Comment by kyleam** [comment]
[ relaying some input from @kylebaron ]

> Requirement 2: passing custom data

This is useful to be able to do. Example: simulating with data set where `TIME` is under a different name.

Idea to consider for allowing adjustments but dropping data argument: allow passing a function that can adjust the data after the join (e.g., renaming a column to `TIME`).

**Comment by seth127** [comment]
# Options

_There are probably other reasonable options, but these are the ones that I'm leaning towards at this point._

## No tables issue

* Don't filter incoming data set when no tables are passed (i.e. default to `.superset` behavior in this case)
  * This is essentially adding the simulated columns to the raw data set coming from `bbr::nm_data()`
* Implement the filtering logic in `bbr.bayes`
  * We read in `nm_data()` and then do the filtering that NONMEM would do.
  * Would probably mean parsing some info from the `$DATA` record via `nmrec`

_For both of these, I'm assuming `nm_join_quick()` just fails when no tables are passed._
## Passing custom data

* **Don't allow passing custom data**
  * Instead find some other way to accomplish the column renaming that @kylebaron mentioned. 
  * Possibly allow passing _additional_ data instead (i.e. another data set that can be joined against the data returned (internally) by `nm_join()`
* **Allow passing custom data** and add the same functionality to `bbr::nm_join()`
  * This would mean we need to constrain `bbr > 1.7.0` for this function (or at least arg) to work
  * I'm still unclear if there's ever a need for this in `bbr::nm_join()`
* **Allow passing custom data** and re-implement the join logic in `bbr.bayes`
  * _I don't really want to do this, mostly for maintenance reasons, but it is an option._

**Comment by seth127** [comment]
My previous comment (listing options I saw) was done in preparation for a discussion with @timwaterhouse @KatherineKayMRG and @kylebaron . The outcome of that discussion was that, at this point, we will take the following approach:

1. Use `bbr::nm_join()` under the hood, in part to more easily support the various arguments and input checking it does already
  a. We will support passing through to the `.files` argument, as well as other `bbr::nm_join()` args.
3. We will _not_ allow passing in custom data, but will instead allow the user to pass a function that modifies the (joined) data. Obviously, we'll need to do some checking on what comes back from this (one proposed check was that the returned value should be a data frame with the same number of rows as the one passed in). 
  a. The primary need for this is accomodate situations where a column needs to be renamed or slightly modified in order for the input data to work correctly with the supplied `mrgsolve` model.
4. We are fine with failing (in all cases) if no tables are found. This is the current `bbr` behavior.
  a. We discussed allowing this for `nm_join_bayes()` but consensus is that this is fine at this point and could potentially be added in the future if there is need for it.

Some outstanding implementation details still need to be ironed out, but I think we have pretty good agreement on the API and behavior at this point.
